apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: In , values: [second-app, first-app]}
    #   - {key: app, operator: NotIn , values: [second-app, first-app]}
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
      - name: second-node
        image: howcool/kube-first-app:2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10 #define how often that should be performed
          initialDelaySeconds: 5 # define how long kubernetes should be wait until it checks the health for the first time
      #- name: ...
      #  image: ...
